package com.gorman.ourmemoryapp.ui.theme

import androidx.compose.ui.graphics.Color

val MemoryRed = Color(0xFF7F0410)
val MemoryRedBright = Color(0xFFBB1020)
val MemoryRedContainer = Color(0xFFF7E4E2)
val MemoryOnRedContainer = Color(0xFF410006)
val MemoryInk = Color(0xFF1F1A1A)
val MemoryInkMuted = Color(0xFF5F5656)
val MemoryPaper = Color(0xFFFFFFFF)
val MemoryPaperLow = Color(0xFFF8F6F5)
val MemoryPaperMid = Color(0xFFF3F0EF)
val MemoryPaperHigh = Color(0xFFF0F0F0)
val MemoryPaperHighest = Color(0xFFE9E5E4)
val MemoryOutline = Color(0xFF857C7B)
val MemoryOutlineVariant = Color(0xFFE2DBDA)
val MemoryRedOnDark = Color(0xFFFFB3AC)
val MemoryRedContainerDark = Color(0xFF6A0A12)
val MemoryOnRedContainerDark = Color(0xFFFFDAD6)
val MemoryNight = Color(0xFF151212)
val MemoryNightLowest = Color(0xFF100D0D)
val MemoryNightLow = Color(0xFF1D1A1A)
val MemoryNightMid = Color(0xFF221E1E)
val MemoryNightHigh = Color(0xFF2C2828)
val MemoryNightHighest = Color(0xFF373232)
val MemoryNightInk = Color(0xFFEDE0DE)
val MemoryNightInkMuted = Color(0xFFD8C2BF)
val MemoryNightOutline = Color(0xFFA08C8A)
val MemoryNightOutlineVariant = Color(0xFF534341)
val MemoryGreenContainer = Color(0xFFDCEBD8)
val MemoryOnGreenContainer = Color(0xFF0F2A12)
val MemoryGreenContainerDark = Color(0xFF28402A)
val MemoryOnGreenContainerDark = Color(0xFFCDE8C8)
